// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nomadlife/CommunityMap.tsx": () => import("../components/mockups/nomadlife/CommunityMap.tsx"),
  "./components/mockups/nomadlife/DiaryHub.tsx": () => import("../components/mockups/nomadlife/DiaryHub.tsx")
};
